// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package fsm

import (
	"sync"
)

// Ensure, that DataStorageMock does implement DataStorage.
// If this is not the case, regenerate this file with moq.
var _ DataStorage = &DataStorageMock{}

// DataStorageMock is a mock implementation of DataStorage.
//
//	func TestSomethingThatUsesDataStorage(t *testing.T) {
//
//		// make and configure a mocked DataStorage
//		mockedDataStorage := &DataStorageMock{
//			DeleteFunc: func(userID int64, key any) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(userID int64, key any) (any, error) {
//				panic("mock out the Get method")
//			},
//			MarshalJSONFunc: func() ([]byte, error) {
//				panic("mock out the MarshalJSON method")
//			},
//			PutFunc: func(userID int64, key any, value any) error {
//				panic("mock out the Put method")
//			},
//			UnmarshalJSONFunc: func(data []byte) error {
//				panic("mock out the UnmarshalJSON method")
//			},
//		}
//
//		// use mockedDataStorage in code that requires DataStorage
//		// and then make assertions.
//
//	}
type DataStorageMock struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(userID int64, key any) error

	// GetFunc mocks the Get method.
	GetFunc func(userID int64, key any) (any, error)

	// MarshalJSONFunc mocks the MarshalJSON method.
	MarshalJSONFunc func() ([]byte, error)

	// PutFunc mocks the Put method.
	PutFunc func(userID int64, key any, value any) error

	// UnmarshalJSONFunc mocks the UnmarshalJSON method.
	UnmarshalJSONFunc func(data []byte) error

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// UserID is the userID argument value.
			UserID int64
			// Key is the key argument value.
			Key any
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// UserID is the userID argument value.
			UserID int64
			// Key is the key argument value.
			Key any
		}
		// MarshalJSON holds details about calls to the MarshalJSON method.
		MarshalJSON []struct {
		}
		// Put holds details about calls to the Put method.
		Put []struct {
			// UserID is the userID argument value.
			UserID int64
			// Key is the key argument value.
			Key any
			// Value is the value argument value.
			Value any
		}
		// UnmarshalJSON holds details about calls to the UnmarshalJSON method.
		UnmarshalJSON []struct {
			// Data is the data argument value.
			Data []byte
		}
	}
	lockDelete        sync.RWMutex
	lockGet           sync.RWMutex
	lockMarshalJSON   sync.RWMutex
	lockPut           sync.RWMutex
	lockUnmarshalJSON sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *DataStorageMock) Delete(userID int64, key any) error {
	if mock.DeleteFunc == nil {
		panic("DataStorageMock.DeleteFunc: method is nil but DataStorage.Delete was just called")
	}
	callInfo := struct {
		UserID int64
		Key    any
	}{
		UserID: userID,
		Key:    key,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(userID, key)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedDataStorage.DeleteCalls())
func (mock *DataStorageMock) DeleteCalls() []struct {
	UserID int64
	Key    any
} {
	var calls []struct {
		UserID int64
		Key    any
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *DataStorageMock) Get(userID int64, key any) (any, error) {
	if mock.GetFunc == nil {
		panic("DataStorageMock.GetFunc: method is nil but DataStorage.Get was just called")
	}
	callInfo := struct {
		UserID int64
		Key    any
	}{
		UserID: userID,
		Key:    key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(userID, key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedDataStorage.GetCalls())
func (mock *DataStorageMock) GetCalls() []struct {
	UserID int64
	Key    any
} {
	var calls []struct {
		UserID int64
		Key    any
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// MarshalJSON calls MarshalJSONFunc.
func (mock *DataStorageMock) MarshalJSON() ([]byte, error) {
	if mock.MarshalJSONFunc == nil {
		panic("DataStorageMock.MarshalJSONFunc: method is nil but DataStorage.MarshalJSON was just called")
	}
	callInfo := struct {
	}{}
	mock.lockMarshalJSON.Lock()
	mock.calls.MarshalJSON = append(mock.calls.MarshalJSON, callInfo)
	mock.lockMarshalJSON.Unlock()
	return mock.MarshalJSONFunc()
}

// MarshalJSONCalls gets all the calls that were made to MarshalJSON.
// Check the length with:
//
//	len(mockedDataStorage.MarshalJSONCalls())
func (mock *DataStorageMock) MarshalJSONCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockMarshalJSON.RLock()
	calls = mock.calls.MarshalJSON
	mock.lockMarshalJSON.RUnlock()
	return calls
}

// Put calls PutFunc.
func (mock *DataStorageMock) Put(userID int64, key any, value any) error {
	if mock.PutFunc == nil {
		panic("DataStorageMock.PutFunc: method is nil but DataStorage.Put was just called")
	}
	callInfo := struct {
		UserID int64
		Key    any
		Value  any
	}{
		UserID: userID,
		Key:    key,
		Value:  value,
	}
	mock.lockPut.Lock()
	mock.calls.Put = append(mock.calls.Put, callInfo)
	mock.lockPut.Unlock()
	return mock.PutFunc(userID, key, value)
}

// PutCalls gets all the calls that were made to Put.
// Check the length with:
//
//	len(mockedDataStorage.PutCalls())
func (mock *DataStorageMock) PutCalls() []struct {
	UserID int64
	Key    any
	Value  any
} {
	var calls []struct {
		UserID int64
		Key    any
		Value  any
	}
	mock.lockPut.RLock()
	calls = mock.calls.Put
	mock.lockPut.RUnlock()
	return calls
}

// UnmarshalJSON calls UnmarshalJSONFunc.
func (mock *DataStorageMock) UnmarshalJSON(data []byte) error {
	if mock.UnmarshalJSONFunc == nil {
		panic("DataStorageMock.UnmarshalJSONFunc: method is nil but DataStorage.UnmarshalJSON was just called")
	}
	callInfo := struct {
		Data []byte
	}{
		Data: data,
	}
	mock.lockUnmarshalJSON.Lock()
	mock.calls.UnmarshalJSON = append(mock.calls.UnmarshalJSON, callInfo)
	mock.lockUnmarshalJSON.Unlock()
	return mock.UnmarshalJSONFunc(data)
}

// UnmarshalJSONCalls gets all the calls that were made to UnmarshalJSON.
// Check the length with:
//
//	len(mockedDataStorage.UnmarshalJSONCalls())
func (mock *DataStorageMock) UnmarshalJSONCalls() []struct {
	Data []byte
} {
	var calls []struct {
		Data []byte
	}
	mock.lockUnmarshalJSON.RLock()
	calls = mock.calls.UnmarshalJSON
	mock.lockUnmarshalJSON.RUnlock()
	return calls
}
