// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package fsm

import (
	"sync"
)

// Ensure, that UserStateStorageMock does implement UserStateStorage.
// If this is not the case, regenerate this file with moq.
var _ UserStateStorage = &UserStateStorageMock{}

// UserStateStorageMock is a mock implementation of UserStateStorage.
//
//	func TestSomethingThatUsesUserStateStorage(t *testing.T) {
//
//		// make and configure a mocked UserStateStorage
//		mockedUserStateStorage := &UserStateStorageMock{
//			ExistsFunc: func(userID int64) (bool, error) {
//				panic("mock out the Exists method")
//			},
//			GetFunc: func(userID int64) (StateID, error) {
//				panic("mock out the Get method")
//			},
//			MarshalJSONFunc: func() ([]byte, error) {
//				panic("mock out the MarshalJSON method")
//			},
//			SetFunc: func(userID int64, stateID StateID) error {
//				panic("mock out the Set method")
//			},
//			UnmarshalJSONFunc: func(data []byte) error {
//				panic("mock out the UnmarshalJSON method")
//			},
//		}
//
//		// use mockedUserStateStorage in code that requires UserStateStorage
//		// and then make assertions.
//
//	}
type UserStateStorageMock struct {
	// ExistsFunc mocks the Exists method.
	ExistsFunc func(userID int64) (bool, error)

	// GetFunc mocks the Get method.
	GetFunc func(userID int64) (StateID, error)

	// MarshalJSONFunc mocks the MarshalJSON method.
	MarshalJSONFunc func() ([]byte, error)

	// SetFunc mocks the Set method.
	SetFunc func(userID int64, stateID StateID) error

	// UnmarshalJSONFunc mocks the UnmarshalJSON method.
	UnmarshalJSONFunc func(data []byte) error

	// calls tracks calls to the methods.
	calls struct {
		// Exists holds details about calls to the Exists method.
		Exists []struct {
			// UserID is the userID argument value.
			UserID int64
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// UserID is the userID argument value.
			UserID int64
		}
		// MarshalJSON holds details about calls to the MarshalJSON method.
		MarshalJSON []struct {
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// UserID is the userID argument value.
			UserID int64
			// StateID is the stateID argument value.
			StateID StateID
		}
		// UnmarshalJSON holds details about calls to the UnmarshalJSON method.
		UnmarshalJSON []struct {
			// Data is the data argument value.
			Data []byte
		}
	}
	lockExists        sync.RWMutex
	lockGet           sync.RWMutex
	lockMarshalJSON   sync.RWMutex
	lockSet           sync.RWMutex
	lockUnmarshalJSON sync.RWMutex
}

// Exists calls ExistsFunc.
func (mock *UserStateStorageMock) Exists(userID int64) (bool, error) {
	if mock.ExistsFunc == nil {
		panic("UserStateStorageMock.ExistsFunc: method is nil but UserStateStorage.Exists was just called")
	}
	callInfo := struct {
		UserID int64
	}{
		UserID: userID,
	}
	mock.lockExists.Lock()
	mock.calls.Exists = append(mock.calls.Exists, callInfo)
	mock.lockExists.Unlock()
	return mock.ExistsFunc(userID)
}

// ExistsCalls gets all the calls that were made to Exists.
// Check the length with:
//
//	len(mockedUserStateStorage.ExistsCalls())
func (mock *UserStateStorageMock) ExistsCalls() []struct {
	UserID int64
} {
	var calls []struct {
		UserID int64
	}
	mock.lockExists.RLock()
	calls = mock.calls.Exists
	mock.lockExists.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *UserStateStorageMock) Get(userID int64) (StateID, error) {
	if mock.GetFunc == nil {
		panic("UserStateStorageMock.GetFunc: method is nil but UserStateStorage.Get was just called")
	}
	callInfo := struct {
		UserID int64
	}{
		UserID: userID,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(userID)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedUserStateStorage.GetCalls())
func (mock *UserStateStorageMock) GetCalls() []struct {
	UserID int64
} {
	var calls []struct {
		UserID int64
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// MarshalJSON calls MarshalJSONFunc.
func (mock *UserStateStorageMock) MarshalJSON() ([]byte, error) {
	if mock.MarshalJSONFunc == nil {
		panic("UserStateStorageMock.MarshalJSONFunc: method is nil but UserStateStorage.MarshalJSON was just called")
	}
	callInfo := struct {
	}{}
	mock.lockMarshalJSON.Lock()
	mock.calls.MarshalJSON = append(mock.calls.MarshalJSON, callInfo)
	mock.lockMarshalJSON.Unlock()
	return mock.MarshalJSONFunc()
}

// MarshalJSONCalls gets all the calls that were made to MarshalJSON.
// Check the length with:
//
//	len(mockedUserStateStorage.MarshalJSONCalls())
func (mock *UserStateStorageMock) MarshalJSONCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockMarshalJSON.RLock()
	calls = mock.calls.MarshalJSON
	mock.lockMarshalJSON.RUnlock()
	return calls
}

// Set calls SetFunc.
func (mock *UserStateStorageMock) Set(userID int64, stateID StateID) error {
	if mock.SetFunc == nil {
		panic("UserStateStorageMock.SetFunc: method is nil but UserStateStorage.Set was just called")
	}
	callInfo := struct {
		UserID  int64
		StateID StateID
	}{
		UserID:  userID,
		StateID: stateID,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	return mock.SetFunc(userID, stateID)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedUserStateStorage.SetCalls())
func (mock *UserStateStorageMock) SetCalls() []struct {
	UserID  int64
	StateID StateID
} {
	var calls []struct {
		UserID  int64
		StateID StateID
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}

// UnmarshalJSON calls UnmarshalJSONFunc.
func (mock *UserStateStorageMock) UnmarshalJSON(data []byte) error {
	if mock.UnmarshalJSONFunc == nil {
		panic("UserStateStorageMock.UnmarshalJSONFunc: method is nil but UserStateStorage.UnmarshalJSON was just called")
	}
	callInfo := struct {
		Data []byte
	}{
		Data: data,
	}
	mock.lockUnmarshalJSON.Lock()
	mock.calls.UnmarshalJSON = append(mock.calls.UnmarshalJSON, callInfo)
	mock.lockUnmarshalJSON.Unlock()
	return mock.UnmarshalJSONFunc(data)
}

// UnmarshalJSONCalls gets all the calls that were made to UnmarshalJSON.
// Check the length with:
//
//	len(mockedUserStateStorage.UnmarshalJSONCalls())
func (mock *UserStateStorageMock) UnmarshalJSONCalls() []struct {
	Data []byte
} {
	var calls []struct {
		Data []byte
	}
	mock.lockUnmarshalJSON.RLock()
	calls = mock.calls.UnmarshalJSON
	mock.lockUnmarshalJSON.RUnlock()
	return calls
}
